// apps/mobile/app/profile.tsx
import { useState, useEffect } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ScrollView, ActivityIndicator } from 'react-native';
import { useRouter } from 'expo-router';
import { trpc } from '@/lib/trpc';
import { useAuth } from '@/lib/auth-context';

export default function Profile() {
  const router = useRouter();
  const { token, logout } = useAuth();
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState<any>(null);
  const [error, setError] = useState('');

  useEffect(() => {
    loadProfile();
  }, []);

  const loadProfile = async () => {
    if (!token) {
      router.replace('/login');
      return;
    }

    try {
      const profile = await trpc.auth.me.query();
      setUser(profile);
    } catch (err: any) {
      setError('Failed to load profile');
      if (err.shape?.code === 'UNAUTHORIZED') {
        await logout();
        router.replace('/login');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleLogout = async () => {
    await logout();
    router.replace('/login');
  };

  if (loading) {
    return (
      <View style={styles.centerContainer}>
        <ActivityIndicator size="large" color="#000" />
        <Text style={styles.loadingText}>Loading profile...</Text>
      </View>
    );
  }

  if (error) {
    return (
      <View style={styles.centerContainer}>
        <Text style={styles.error}>{error}</Text>
      </View>
    );
  }

  return (
    <ScrollView style={styles.container}>
      <View style={styles.content}>
        <Text style={styles.title}>Profile</Text>
        <Text style={styles.subtitle}>Your account information</Text>

        {user && (
          <View style={styles.card}>
            <View style={styles.field}>
              <Text style={styles.label}>Name</Text>
              <Text style={styles.value}>{user.firstName} {user.lastName}</Text>
            </View>

            <View style={styles.field}>
              <Text style={styles.label}>Email</Text>
              <Text style={styles.value}>{user.email}</Text>
            </View>

            <View style={styles.field}>
              <Text style={styles.label}>Role</Text>
              <Text style={[styles.value, styles.capitalize]}>{user.role}</Text>
            </View>

            <View style={styles.field}>
              <Text style={styles.label}>Account Status</Text>
              <Text style={styles.value}>{user.isActive ? 'Active' : 'Inactive'}</Text>
            </View>

            <View style={styles.field}>
              <Text style={styles.label}>Member Since</Text>
              <Text style={styles.value}>{new Date(user.createdAt).toLocaleDateString()}</Text>
            </View>
          </View>
        )}

        <TouchableOpacity
          style={styles.logoutButton}
          onPress={handleLogout}
        >
          <Text style={styles.logoutButtonText}>Logout</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.homeButton}
          onPress={() => router.push('/')}
        >
          <Text style={styles.homeButtonText}>Back to Home</Text>
        </TouchableOpacity>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9fafb',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f9fafb',
  },
  content: {
    padding: 20,
    paddingTop: 60,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 8,
    textAlign: 'center',
    color: '#111',
  },
  subtitle: {
    fontSize: 16,
    color: '#666',
    marginBottom: 32,
    textAlign: 'center',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: 20,
  },
  field: {
    marginBottom: 20,
  },
  label: {
    fontSize: 12,
    fontWeight: '600',
    color: '#666',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  value: {
    fontSize: 18,
    color: '#111',
  },
  capitalize: {
    textTransform: 'capitalize',
  },
  logoutButton: {
    backgroundColor: '#dc2626',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 12,
  },
  logoutButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  homeButton: {
    backgroundColor: '#f3f4f6',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  homeButtonText: {
    color: '#111',
    fontSize: 16,
    fontWeight: '600',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#666',
  },
  error: {
    fontSize: 16,
    color: '#dc2626',
    textAlign: 'center',
  },
});

// apps/frontend/src/routes/profile/+page.svelte
<script lang="ts">
  import { trpc } from '$lib/trpc';
  import { auth } from '$lib/stores/auth';
  import { goto } from '$app/navigation';
  import { onMount } from 'svelte';

  let loading = true;
  let user: any = null;
  let error = '';

  onMount(async () => {
    if (!$auth.token) {
      goto('/login');
      return;
    }

    try {
      user = await trpc.auth.me.query();
      loading = false;
    } catch (err: any) {
      error = 'Failed to load profile';
      loading = false;
      if (err.shape?.code === 'UNAUTHORIZED') {
        auth.logout();
        goto('/login');
      }
    }
  });

  function handleLogout() {
    auth.logout();
    goto('/login');
  }
</script>

<main class="min-h-screen flex items-center justify-center bg-gray-50 px-4">
  <div class="max-w-md w-full space-y-8">
    <div class="text-center">
      <h1 class="text-4xl font-bold text-gray-900">Profile</h1>
      <p class="mt-2 text-gray-600">Your account information</p>
    </div>

    {#if loading}
      <div class="text-center py-8">
        <p class="text-gray-600">Loading...</p>
      </div>
    {:else if error}
      <div class="bg-red-50 border border-red-200 rounded-lg p-4">
        <p class="text-red-600 text-center">{error}</p>
      </div>
    {:else if user}
      <div class="bg-white rounded-lg shadow p-6 space-y-4">
        <div>
          <label class="text-sm font-semibold text-gray-600">Name</label>
          <p class="text-lg text-gray-900">{user.firstName} {user.lastName}</p>
        </div>

        <div>
          <label class="text-sm font-semibold text-gray-600">Email</label>
          <p class="text-lg text-gray-900">{user.email}</p>
        </div>

        <div>
          <label class="text-sm font-semibold text-gray-600">Role</label>
          <p class="text-lg text-gray-900 capitalize">{user.role}</p>
        </div>

        <div>
          <label class="text-sm font-semibold text-gray-600">Account Status</label>
          <p class="text-lg text-gray-900">{user.isActive ? 'Active' : 'Inactive'}</p>
        </div>

        <div>
          <label class="text-sm font-semibold text-gray-600">Member Since</label>
          <p class="text-lg text-gray-900">{new Date(user.createdAt).toLocaleDateString()}</p>
        </div>

        <div class="pt-4 space-y-2">
          <button
            on:click={handleLogout}
            class="w-full bg-red-600 text-white py-2 px-4 rounded-lg hover:bg-red-700 transition cursor-pointer flex items-center justify-center gap-2"
          >
            <iconify-icon icon="solar:logout-bold-duotone" width="20" height="20"></iconify-icon>
            Logout
          </button>

          <a
            href="/"
            class="block w-full text-center bg-black text-white py-2 px-4 rounded-lg hover:bg-white hover:text-black hover:border hover:border-black transition flex items-center justify-center gap-2"
          >
            <iconify-icon icon="solar:home-bold-duotone" width="20" height="20"></iconify-icon>
            Back to Home
          </a>
        </div>
      </div>
    {/if}
  </div>
</main>
